language: r
sudo: required
cache: packages
dist: trusty
r: release
r_binary_packages:
    - devtools
r_github_packages:
    - klutometis/roxygen
    - r-lib/rcmdcheck
    - jimhester/lintr
    - jimhester/covr
script:
  - R -e 'devtools::install("."); r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); l <- lintr::lint_package("."); if (length(r$errors) > 0) { devtools::test() }; print(l); quit(save = "no", status = if (length(c(r$errors, r$warnings, r$notes, l)) > 0) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - R -e 'library(covr); coveralls()'
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
